name: Remote repo checkout test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to be used for running the tests
        default: main
        required: true
        type: string

jobs:
  checkout:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set the variables
        id: variables
        env:
          BRANCH: 'main'
        run: |
          echo "BRANCH=${{ github.event.inputs.branch || env.BRANCH }}" >> $GITHUB_ENV

      # - name: Retrieve the deploy key for fi-po-tests and decode it
      #   env:
      #     DEPLOY_KEY_BASE64: ${{ secrets.DEPLOY_KEY_FI_PO_TESTS }}
      #   run: |
      #     (echo "$DEPLOY_KEY_BASE64" | base64 -d) > fi-po-tests-key

      - uses: actions/checkout@v3
        with:
          repository: telia-company/fi-po-tests
          ref: ${{env.BRANCH}} # Run for branch given as input or set as default
          ssh-key: ${{ secrets.DEPLOY_KEY_FI_PO_TESTS }}
