name: Remote repo checkout test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to be used for running the tests
        default: main
        required: true
        type: string

jobs:
  checkout:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set the variables
        id: variables
        env:
          BRANCH: 'main'
        run: |
          echo "BRANCH=${{ github.event.inputs.branch || env.BRANCH }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }} # Run for branch given as input or set as default

      - name: Get submodule SHAs
        id: sha
        run: |
          echo "fi-po-tests=`git submodule status fi-po-tests | awk -F ' ' '{print $1}' | cut -c2-`" >> $GITHUB_OUTPUT

      - name: Checkout submodule fi-po-tests
        uses: actions/checkout@v3
        with:
          repository: telia-company/fi-po-tests
          ref: ${{ steps.sha.outputs.fi-po-tests }}
          path: fi-po-tests
          ssh-key: ${{ secrets.DEPLOY_KEY_FI_PO_TESTS }}
